// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdxGMG8ll5SxTgQ7JQEqxKkVmkSVzjzkM',
    appId: '1:503194045454:web:6e92bf8560dd0be63f005f',
    messagingSenderId: '503194045454',
    projectId: 'rideco-174e4',
    authDomain: 'rideco-174e4.firebaseapp.com',
    storageBucket: 'rideco-174e4.firebasestorage.app',
    measurementId: 'G-LJ1P7KDP4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uLSFy7CiRh0tRvVWv1Qs-C-VvCN4JLc',
    appId: '1:503194045454:android:6e63504d51c8a18f3f005f',
    messagingSenderId: '503194045454',
    projectId: 'rideco-174e4',
    storageBucket: 'rideco-174e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeTSUoSZqFbxFrJML7949PsxKQA4HGHuI',
    appId: '1:503194045454:ios:cd3a95b3520521173f005f',
    messagingSenderId: '503194045454',
    projectId: 'rideco-174e4',
    storageBucket: 'rideco-174e4.firebasestorage.app',
    iosBundleId: 'com.example.rideco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeTSUoSZqFbxFrJML7949PsxKQA4HGHuI',
    appId: '1:503194045454:ios:cd3a95b3520521173f005f',
    messagingSenderId: '503194045454',
    projectId: 'rideco-174e4',
    storageBucket: 'rideco-174e4.firebasestorage.app',
    iosBundleId: 'com.example.rideco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdxGMG8ll5SxTgQ7JQEqxKkVmkSVzjzkM',
    appId: '1:503194045454:web:e8e397b011ef7eb53f005f',
    messagingSenderId: '503194045454',
    projectId: 'rideco-174e4',
    authDomain: 'rideco-174e4.firebaseapp.com',
    storageBucket: 'rideco-174e4.firebasestorage.app',
    measurementId: 'G-V5XSM16NDM',
  );
}
